language: node_js

node_js: ['8']

install:
- yarn install

script:
- npm run build
- npm run lint
- npm run test:coverage

before_deploy:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc

deploy:
  provider: script
  skip_cleanup: true
  script: npm publish .
  on:
    tags: true
